### ISSUE TITLE
Build: Could not find net.mamoe.yamlkt:yamlkt-mingwx64:0.9.0.

### ISSUE THREAD

**Issue by Josef-Vonasek** [Him188/yamlkt#29]
```
   > Could not find net.mamoe.yamlkt:yamlkt-mingwx64:0.9.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/net/mamoe/yamlkt/yamlkt-mingwx64/0.9.0/yamlkt-mingwx64-0.9.0.pom
     Required by:
         project : > net.mamoe.yamlkt:yamlkt:0.9.0
```
The issue seems to be that the artifacts are published on maven in `yamlkt-mingwX64` instead of `yamlkt-mingwx64`.

**Comment by Him188** [comment]
Reproduced with `0.9.0`, but failed to reproduce with `0.10.0-dev-1` (a test version based on master).

![image](https://user-images.githubusercontent.com/12100985/123971549-bd843700-d9ec-11eb-9070-dd23ebcbe4d4.png)

Seems this is because of a change included in Kotlin 1.5. Updating yamlkt to the incoming `0.10.0` will resolve this problem.
