### ISSUE TITLE
Js version is failing on Kotlin 1.8.10 serialization 1.5.0-RC

### ISSUE THREAD

**Issue by SPC-code** [Him188/yamlkt#54]
Error message: `ReferenceError: Byte is not defined`. It seems like this line is the source: https://github.com/Him188/yamlkt/blob/66906a195b0014f46ca05167d941e05cc6eb2291/yamlkt/src/jsMain/kotlin/net.mamoe.yamlkt/internal/serializeImpl.js.kt#L16.

**Comment by Him188** [comment]
Can you share console logs and how to reproduce the problem?

**Comment by ncipollo** [comment]
This change seemed to fix the issue for me when I ran the tests within the project (had to move some stuff around & update gradle to run tests, but was able to reproduce the issue before I made this change):
https://github.com/ncipollo/yamlkt/blob/ncipollo/54/kotlin-1.8-fix/yamlkt/src/jsMain/kotlin/net.mamoe.yamlkt/internal/serializeImpl.js.kt

Basically changed that file to simply use the kclass, instead of the JS class. I'm guessing Byte doesn't actually exist as a class in the js kotlin standard library.

**Comment by Him188** [comment]
I think this issue should be resolved in 0.13.0. Can you confirm that on your machine?

**Comment by Him188** [comment]
Never mind. I will keep this issue open for a while to see if anyone encounters the same problem in 0.13.0.

**Comment by ncipollo** [comment]
If you push 0.13.0 to maven or push a snapshot I can test real quick today.

**Comment by Him188** [comment]
> If you push 0.13.0 to maven or push a snapshot I can test real quick today.

I've already released 0.13.0 on Maven Central, but it may take some time to be visible publicly.

**Comment by ncipollo** [comment]
Cool, I'll try and check it out today.

**Comment by ncipollo** [comment]
`0.13.0` looks good in my repo. The JS tests which were previously failing are now passing!

- https://github.com/ncipollo/tix-core/commit/b85dd7f3e53b5f373a0b9c09d071070063967715
- https://github.com/ncipollo/tix-core/actions/runs/4852072618
